# Generated by Django 3.2.5 on 2021-08-13 11:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabet and whitespace characters are allowed.'), django.core.validators.MinLengthValidator(3, 'Minimum length of 3 letters required.')]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabet and whitespace characters are allowed.'), django.core.validators.MinLengthValidator(3, 'Minimum length of 3 letters required.')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabet and whitespace characters are allowed.'), django.core.validators.MinLengthValidator(3, 'Minimum length of 3 letters required.')]),
        ),
    ]
