# Generated by Django 3.2.5 on 2021-08-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_published',)},
        ),
    ]
