# Generated by Django 3.2.5 on 2021-08-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
