# Generated by Django 3.2.5 on 2021-08-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile/images/default.jpg', null=True, upload_to='profile/images/'),
        ),
    ]
